### ISSUE TITLE
Adapter funktioniert nicht mit Admin 6.2.20

### ISSUE THREAD

**Issue by Semmy100** [rg-engineering/ioBroker.minmax#44]
Ich habe den Adapter installiert und auch eine Instanz hinzu gefügt und auch gestartet. Dann müsste im Objekte-Fenster rechts bei den Zahnrädern der Adapter minmax auch aktiviert werden können, es ist jedoch kein Eintrag minmax vorhanden.

**Comment by rg-engineering** [comment]
@Semmy100 Die Beschreibung passt aber nicht zur Überschrift? Bei mir läuft der Adapter unter admin 6.2.21. Ein paar mehr Infos wären hilfreich...
